--Query 1
--by hospital and address
SELECT  h.NOMBRE, hs.DIRECCION, COUNT(*) AS cnt  FROM hospital_visita hv
INNER JOIN VICTIMA v ON v.ID_VICTIMA = hv.ID_VICTIMA
INNER JOIN HOSPITAL_SEDE hs ON hv.id_hospital_sede = hs.ID_HOSPITAL_SEDE 
INNER JOIN HOSPITAL h ON h.ID_HOSPITAL = hs.ID_HOSPITAL
WHERE v.FECHA_MUERTE IS NOT NULL
GROUP BY h.NOMBRE, hs.DIRECCION
ORDER BY h.NOMBRE,hs.DIRECCION ASC;

--by hospital general
SELECT  h.NOMBRE, COUNT(*) AS cnt  FROM hospital_visita hv
INNER JOIN VICTIMA v ON v.ID_VICTIMA = hv.ID_VICTIMA
INNER JOIN HOSPITAL_SEDE hs ON hv.id_hospital_sede = hs.ID_HOSPITAL_SEDE 
INNER JOIN HOSPITAL h ON h.ID_HOSPITAL = hs.ID_HOSPITAL
WHERE v.FECHA_MUERTE IS NOT NULL
GROUP BY h.NOMBRE
ORDER BY h.NOMBRE ASC;



--Consulta 2
SELECT v.NOMBRE_VICTIMA , v.APELLIDO_VICTIMA, t.NOMBRE , tv.EFECTIVIDAD_EN_VICTIMA 
FROM VICTIMA v 
INNER JOIN TRATAMIENTO_VICTIMA tv ON tv.ID_VICTIMA = v.ID_VICTIMA 
INNER JOIN TRATAMIENTO t ON t.ID_TRATAMIENTO = tv.ID_TRATAMIENTO 
INNER JOIN ESTADO e ON e.ID_ESTADO = v.ID_ESTADO 
WHERE t.NOMBRE = 'Transfusiones de sangre' AND tv.EFECTIVIDAD_EN_VICTIMA > 5 AND e.DESCRIPCION = 'En cuarentena';



--3. Mostrar el nombre, apellido y dirección de las víctimas fallecidas con
--más de tres personas asociadas.
SELECT v.NOMBRE_VICTIMA, v.APELLIDO_VICTIMA, v.DIRECCION_VICTIMA --, COUNT(va.ID_VICTIMA) AS NUMERO_ASOCIADOS
FROM VICTIMA v 
INNER JOIN VICTIMA_ASOCIADO va ON va.ID_VICTIMA = v.ID_VICTIMA 
WHERE v.FECHA_MUERTE IS NOT NULL
GROUP BY  v.NOMBRE_VICTIMA, v.APELLIDO_VICTIMA, v.DIRECCION_VICTIMA
HAVING COUNT(va.ID_VICTIMA) > 3
ORDER BY v.NOMBRE_VICTIMA, v.APELLIDO_VICTIMA ASC;



--4. Mostrar el nombre y apellido de todas las víctimas en estado
--“Suspendida” que tuvieron contacto físico de tipo “Beso” con más de
--2 de sus asociados.

SELECT v.NOMBRE_VICTIMA, v.APELLIDO_VICTIMA--, COUNT(v.ID_VICTIMA) AS asociado_count
FROM VICTIMA v 
INNER JOIN ESTADO e ON e.ID_ESTADO = v.ID_ESTADO 
INNER JOIN VICTIMA_ASOCIADO_CONTACTO vac ON vac.ID_VICTIMA = v.ID_VICTIMA 
INNER JOIN CONTACTO c ON c.ID_CONTACTO = vac.ID_CONTACTO 
WHERE e.DESCRIPCION = 'Suspendida' AND c.CONTACTO_TIPO = 'Beso'
GROUP BY  v.NOMBRE_VICTIMA, v.APELLIDO_VICTIMA 
HAVING COUNT(v.ID_VICTIMA) > 2
ORDER BY v.NOMBRE_VICTIMA, v.APELLIDO_VICTIMA ASC;



--5. Top 5 de víctimas que más tratamientos se han aplicado del
--tratamiento “Oxígeno”.
SELECT * FROM (
	SELECT v.NOMBRE_VICTIMA, v.APELLIDO_VICTIMA--, COUNT(v.ID_VICTIMA)
	FROM VICTIMA v 
	INNER JOIN TRATAMIENTO_VICTIMA tv ON tv.ID_VICTIMA  = v.ID_VICTIMA 
	INNER JOIN TRATAMIENTO t ON t.ID_TRATAMIENTO = tv.ID_TRATAMIENTO 
	WHERE t.NOMBRE = 'Oxigeno'
	GROUP BY v.NOMBRE_VICTIMA, v.APELLIDO_VICTIMA
	ORDER BY COUNT(v.ID_VICTIMA) DESC
)
where ROWNUM <= 5;



--6. Mostrar el nombre, el apellido y la fecha de fallecimiento de todas las
--víctimas que se movieron por la dirección “1987 Delphine Well” a los
--cuales se les aplicó "Manejo de la presión arterial" como tratamiento.
SELECT v.NOMBRE_VICTIMA, v.APELLIDO_VICTIMA, v.FECHA_MUERTE, u.DESCRIPCION, t.NOMBRE
FROM VICTIMA v 
INNER JOIN UBICACION_VICTIMA uv ON v.ID_VICTIMA = uv.ID_VICTIMA 
INNER JOIN UBICACION u ON u.ID_UBICACION = uv.ID_UBICACION 
INNER JOIN TRATAMIENTO_VICTIMA tv ON tv.ID_VICTIMA = v.ID_VICTIMA 
INNER JOIN TRATAMIENTO t ON tv.ID_TRATAMIENTO = t.ID_TRATAMIENTO 
WHERE u.DESCRIPCION = '1987 Delphine Well' AND t.NOMBRE = 'Manejo de la presion arterial' AND v.FECHA_MUERTE IS NOT NULL;



--7. Mostrar nombre, apellido y dirección de las víctimas que tienen menos
--de 2 allegados los cuales hayan estado en un hospital y que se le
--hayan aplicado únicamente dos tratamientos.
SELECT v.NOMBRE_VICTIMA, v.APELLIDO_VICTIMA
FROM VICTIMA v 
INNER JOIN VICTIMA_ASOCIADO va ON va.ID_VICTIMA = v.ID_VICTIMA 
INNER JOIN ASOCIADO a ON a.ID_ASOCIADO  = va.ID_ASOCIADO
INNER JOIN TRATAMIENTO_VICTIMA tv ON tv.ID_VICTIMA = v.ID_VICTIMA 
INNER JOIN TRATAMIENTO t ON t.ID_TRATAMIENTO = tv.ID_TRATAMIENTO
GROUP BY  v.NOMBRE_VICTIMA, v.APELLIDO_VICTIMA
HAVING COUNT(DISTINCT va.ID_ASOCIADO) < 2 AND COUNT(DISTINCT t.ID_TRATAMIENTO) = 2;



--8. Mostrar el número de mes de la fecha de la primera sospecha,
--nombre y apellido de las víctimas que más tratamientos se han
--aplicado y las que menos. (Todo en una misma consulta).
SELECT * FROM (
  SELECT v.NOMBRE_VICTIMA, v.APELLIDO_VICTIMA, EXTRACT(MONTH FROM v.FECHA_PRIMERA_SOSPECHA) AS MES --,  COUNT(t.ID_TRATAMIENTO) AS NUM_TRATAMIENTOS
  FROM VICTIMA v 
  INNER JOIN TRATAMIENTO_VICTIMA tv ON tv.ID_VICTIMA = v.ID_VICTIMA 
  INNER JOIN TRATAMIENTO t ON t.ID_TRATAMIENTO = tv.ID_TRATAMIENTO 
  GROUP BY v.NOMBRE_VICTIMA, v.APELLIDO_VICTIMA, v.FECHA_PRIMERA_SOSPECHA
  ORDER BY COUNT(t.ID_TRATAMIENTO)  DESC
  FETCH FIRST 5 ROWS ONLY
) 
UNION ALL
SELECT * FROM (
  SELECT v.NOMBRE_VICTIMA, v.APELLIDO_VICTIMA, EXTRACT(MONTH FROM v.FECHA_PRIMERA_SOSPECHA) AS MES --,  COUNT(t.ID_TRATAMIENTO) AS NUM_TRATAMIENTOS
  FROM VICTIMA v 
  INNER JOIN TRATAMIENTO_VICTIMA tv ON tv.ID_VICTIMA = v.ID_VICTIMA 
  INNER JOIN TRATAMIENTO t ON t.ID_TRATAMIENTO = tv.ID_TRATAMIENTO 
  GROUP BY v.NOMBRE_VICTIMA, v.APELLIDO_VICTIMA, v.FECHA_PRIMERA_SOSPECHA
  ORDER BY COUNT(t.ID_TRATAMIENTO)  ASC
  FETCH FIRST 5 ROWS ONLY
);



--9. Mostrar el porcentaje de víctimas que le corresponden a cada
--hospital.
SELECT h.NOMBRE,  ROUND (COUNT(v.ID_VICTIMA) * 100 / (SELECT COUNT(*) FROM (
SELECT v.ID_VICTIMA, hs.ID_HOSPITAL
FROM VICTIMA v 
INNER JOIN hospital_visita hv ON hv.id_victima = v.ID_VICTIMA 
INNER JOIN HOSPITAL_SEDE hs ON hs.ID_HOSPITAL_SEDE = hv.id_hospital_sede
INNER JOIN HOSPITAL h ON h.ID_HOSPITAL = hs.ID_HOSPITAL
GROUP BY v.ID_VICTIMA, hs.ID_HOSPITAL
)), 2) AS PERCENTAGE
FROM VICTIMA v 
INNER JOIN hospital_visita hv ON hv.id_victima = v.ID_VICTIMA 
INNER JOIN HOSPITAL_SEDE hs ON hs.ID_HOSPITAL_SEDE = hv.id_hospital_sede
INNER JOIN HOSPITAL h ON h.ID_HOSPITAL = hs.ID_HOSPITAL
GROUP BY h.NOMBRE;
	


--10. Mostrar el porcentaje del contacto físico más común de cada
--hospital de la siguiente manera: nombre de hospital, nombre del
--contacto físico, porcentaje de víctimas.
SELECT  tn.NOMBRE, tn.CONTACTO_TIPO,  ROUND( COUNT(v2.ID_VICTIMA) * 100 /(
SELECT COUNT(v2.ID_VICTIMA) FROM (
SELECT DISTINCT h.ID_HOSPITAL, h.NOMBRE, c.CONTACTO_TIPO, t.NUM_CONTACTOS, t.RANK
FROM HOSPITAL h
INNER JOIN HOSPITAL_SEDE hs ON hs.ID_HOSPITAL = h.ID_HOSPITAL 
INNER JOIN hospital_visita hv ON hs.ID_HOSPITAL_SEDE = hv.id_hospital_sede
INNER JOIN VICTIMA v ON hv.id_victima = v.ID_VICTIMA 
INNER JOIN VICTIMA_ASOCIADO_CONTACTO vac ON vac.ID_VICTIMA = v.ID_VICTIMA 
INNER JOIN CONTACTO c ON c.ID_CONTACTO = vac.ID_CONTACTO 
INNER JOIN (
  SELECT h.ID_HOSPITAL, c.CONTACTO_TIPO, COUNT(*) AS NUM_CONTACTOS,
    ROW_NUMBER() OVER (PARTITION BY h.ID_HOSPITAL ORDER BY COUNT(*) DESC) AS RANK
  FROM HOSPITAL h
  INNER JOIN HOSPITAL_SEDE hs ON hs.ID_HOSPITAL = h.ID_HOSPITAL 
  INNER JOIN hospital_visita hv ON hs.ID_HOSPITAL_SEDE = hv.id_hospital_sede
  INNER JOIN VICTIMA v ON hv.id_victima = v.ID_VICTIMA 
  INNER JOIN VICTIMA_ASOCIADO_CONTACTO vac ON vac.ID_VICTIMA = v.ID_VICTIMA 
  INNER JOIN CONTACTO c ON c.ID_CONTACTO = vac.ID_CONTACTO 
  GROUP BY h.ID_HOSPITAL, c.CONTACTO_TIPO
) t ON t.ID_HOSPITAL = h.ID_HOSPITAL AND t.CONTACTO_TIPO = c.CONTACTO_TIPO AND t.RANK = 1
) tn
INNER JOIN HOSPITAL_SEDE hs2 ON hs2.ID_HOSPITAL = tn.ID_HOSPITAL
INNER JOIN hospital_visita hv2 ON hv2.id_hospital_sede = hs2.id_hospital_sede
INNER JOIN VICTIMA v2 ON v2.ID_VICTIMA = hv2.ID_VICTIMA
),2 ) AS PORCENTAJE
FROM (
SELECT DISTINCT h.ID_HOSPITAL, h.NOMBRE, c.CONTACTO_TIPO, t.NUM_CONTACTOS, t.RANK
FROM HOSPITAL h
INNER JOIN HOSPITAL_SEDE hs ON hs.ID_HOSPITAL = h.ID_HOSPITAL 
INNER JOIN hospital_visita hv ON hs.ID_HOSPITAL_SEDE = hv.id_hospital_sede
INNER JOIN VICTIMA v ON hv.id_victima = v.ID_VICTIMA 
INNER JOIN VICTIMA_ASOCIADO_CONTACTO vac ON vac.ID_VICTIMA = v.ID_VICTIMA 
INNER JOIN CONTACTO c ON c.ID_CONTACTO = vac.ID_CONTACTO 
INNER JOIN (
  SELECT h.ID_HOSPITAL, c.CONTACTO_TIPO, COUNT(*) AS NUM_CONTACTOS,
    ROW_NUMBER() OVER (PARTITION BY h.ID_HOSPITAL ORDER BY COUNT(*) DESC) AS RANK
  FROM HOSPITAL h
  INNER JOIN HOSPITAL_SEDE hs ON hs.ID_HOSPITAL = h.ID_HOSPITAL 
  INNER JOIN hospital_visita hv ON hs.ID_HOSPITAL_SEDE = hv.id_hospital_sede
  INNER JOIN VICTIMA v ON hv.id_victima = v.ID_VICTIMA 
  INNER JOIN VICTIMA_ASOCIADO_CONTACTO vac ON vac.ID_VICTIMA = v.ID_VICTIMA 
  INNER JOIN CONTACTO c ON c.ID_CONTACTO = vac.ID_CONTACTO 
  GROUP BY h.ID_HOSPITAL, c.CONTACTO_TIPO
) t ON t.ID_HOSPITAL = h.ID_HOSPITAL AND t.CONTACTO_TIPO = c.CONTACTO_TIPO AND t.RANK = 1
) tn
INNER JOIN HOSPITAL_SEDE hs2 ON hs2.ID_HOSPITAL = tn.ID_HOSPITAL
INNER JOIN hospital_visita hv2 ON hv2.id_hospital_sede = hs2.id_hospital_sede
INNER JOIN VICTIMA v2 ON v2.ID_VICTIMA = hv2.ID_VICTIMA
GROUP BY tn.NOMBRE, tn.CONTACTO_TIPO;











