--create temp table
CREATE TABLE temp(
id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE_VICTIMA VARCHAR2(100) NULL,
APELLIDO_VICTIMA VARCHAR2(100) NULL,
DIRECCION_VICTIMA VARCHAR2(100) NULL,
FECHA_PRIMERA_SOSPECHA VARCHAR2(100) NULL,
FECHA_CONFIRMACION VARCHAR2(100) NULL,
FECHA_MUERTE VARCHAR2(100) NULL,
ESTADO_VICTIMA VARCHAR2(100) NULL,
NOMBRE_ASOCIADO VARCHAR2(100) NULL,
APELLIDO_ASOCIADO VARCHAR2(100) NULL,
FECHA_CONOCIO VARCHAR2(100) NULL,
CONTACTO_FISICO VARCHAR2(100) NULL,
FECHA_INICIO_CONTACTO VARCHAR2(100) NULL,
FECHA_FIN_CONTACTO VARCHAR2(100) NULL,
NOMBRE_HOSPITAL VARCHAR2(100) NULL,
DIRECCION_HOSPITAL VARCHAR2(100) NULL,
UBICACION_VICTIMA VARCHAR2(100) NULL,
FECHA_LLEGADA VARCHAR2(100) NULL,
FECHA_RETIRO VARCHAR2(100) NULL,
TRATAMIENTO VARCHAR2(100) NULL,
EFECTIVIDAD  VARCHAR2(100) NULL,
FECHA_INICIO_TRATAMIENTO VARCHAR2(100) NULL,
FECHA_FIN_TRATAMIENTO VARCHAR2(100) NULL,
EFECTIVIDAD_EN_VICTIMA  VARCHAR2(100) NULL
);


DROP TABLE temp;

SELECT * FROM temp WHERE ESTADO_VICTIMA='ESTADO_VICTIMA';
DELETE FROM TEMP  WHERE ESTADO_VICTIMA='ESTADO_VICTIMA';

SELECT * FROM TEMP;

--create main tables
DELETE FROM TEMP;


